### ISSUE TITLE
bug: connection string example is inconsistent with implementation

### ISSUE THREAD

**Issue by houz42** [beyondstorage/go-storage#717] opened 2021-08-23 12:27 UTC
The [document](https://beyondstorage.io/docs/go-storage/operations/index#how-to-initialize-a-servicerstorager) shows an example connection string:
> `s3://?credential=hmac:xxxx:xxxx&endpoint=http://s3.us-east-2.amazonaws.com`

While the endpoint in it will not be parsed correctly by the s3 service.
The s3 service uses go-endpoint to parse the endpoint value, which defines endpoints as the form of `http:s3.us-east-2.amazonaws.com`, no `//` after the `http:`

I am using:
- go-storage: v4.4.1
- s3-service: v2.3.0

By the way, I'am happy to fix it, but not sure which solution is preferred:
- make go-endpoint respect the `//` notation,
- or update the doc

**Comment by Xuanwo** [comment] 2021-08-23 13:30
Oooops, our docs is incorrect.

We need to use `http:s3.us-east-2.amazonaws.com` here.

Can you send a PR to site to fix it? Thanks so much!

**Comment by Xuanwo** [comment] 2021-08-23 13:56
And the problem is so common that we are considering add support for `://` too.

**Comment by Xuanwo** [comment] 2021-08-23 15:53
For your convenience: the docs located at https://github.com/beyondstorage/site/blob/master/docs/go-storage/operations/index.md

**Comment by Xuanwo** [comment] 2021-08-24 02:15
Fixed in https://github.com/beyondstorage/site/pull/192, thanks for report!

**Closed** 2021-08-24 02:16 UTC
